PostgreSQL does not like to ORDER BY by something which is not in DISTINCT.
Addressing
org.postgresql.util.PSQLException: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1525)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1309)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:188)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:452)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:354)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:347)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:651)
	at com.redhat.rhn.common.db.NamedPreparedStatement.execute(NamedPreparedStatement.java:139)
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:454)
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:431)
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:335)
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:340)
	at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:280)
	at com.redhat.rhn.common.db.datasource.SelectMode.execute(SelectMode.java:105)
	at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:57)
	at com.redhat.rhn.manager.system.SystemManager.groupList(SystemManager.java:639)
	at com.redhat.rhn.frontend.action.systems.SystemGroupListSetupAction.execute(SystemGroupListSetupAction.java:63)