1654647 - Capture return bind var from bulk_set_custom_value calls.
Add a return bind variable to the rhn_server.bulk_set_custom_value
PL/SQL call definition, and capture it in SystemManager to prevent an
ISE when attempting to set custom info keys via SSM.

PL/SQL was throwing an error because the return value wasn't being
captured by Java persistence layer.

PL/SQL error encountered:

ERROR
com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction.
Rolling back
javax.servlet.ServletException: com.redhat.rhn.common.db.WrappedSQLException:
ORA-06550: line 1, column 7:
PLS-00221: 'BULK_SET_CUSTOM_VALUE' is not a procedure or is undefined
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored

Signed-off-by: Laurence Rochfort <laurence.rochfort@oracle.com>
Reviewed-by: Yinbo Wang <yinbo.wang@oracle.com>