Workaround httplib in 2.4 which did not have the responses dictionary.
Addressing
  File "/usr/lib/python2.4/site-packages/spacewalk/server/apacheRequest.py", line 368, in response
    self.req.send_http_header()
  File "/usr/share/rhn/wsgi/wsgiRequest.py", line 70, in send_http_header
    self.status = self.status + " " +  httplib.responses[int(self.status)]
AttributeError: 'module' object has no attribute 'responses'