add save_traceback even into this branch
addressing:
Traceback (most recent call last):
  File "/usr/bin/rhncfg-client", line 34, in ?
    sys.exit(Main().main() or 0)
  File "/usr/share/rhn/config_common/rhn_main.py", line 170, in main
    repo = getattr(repo_module, self.repository_class_name)()
  File "/usr/share/rhn/config_client/rpc_cli_repository.py", line 32, in __init__
    repository.RPC_Repository.__init__(self, setup_network)
  File "/usr/share/rhn/config_common/repository.py", line 301, in __init__
    x_server.registration.welcome_message()
  File "/usr/lib/python2.4/xmlrpclib.py", line 1096, in __call__
    return self.__send(self.__name, args)
  File "/usr/share/rhn/config_common/rpc_wrapper.py", line 221, in _request
    return self._call_function(rpclib.Server._request, (self, methodname, params))
  File "/usr/share/rhn/config_common/rpc_wrapper.py", line 175, in _call_function
    raise e, None, save_traceback
UnboundLocalError: local variable 'save_traceback' referenced before assignment

This has been ommited in commit 86ec92b1c0221a9bb51e0f032f1800b349972036