OpenSSL.SSL namespace conflicts with rhn.SSL
fixing
  File "/usr/sbin/rhn_check", line 142, in __get_action
    except SSL.Error:
<class 'AttributeError'>: 'module' object has no attribute 'Error'