subelement_dumper_classes must be defined before they are used
addressing
Traceback (most recent call last):
  File "/usr/bin/rhn-satellite-exporter", line 21, in ?
    from spacewalk.satellite_tools.disk_dumper import iss
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/disk_dumper/iss.py", line 21, in ?
    import dumper
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/disk_dumper/dumper.py", line 28, in ?
    from spacewalk.satellite_tools.exporter import exportLib, xmlWriter
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/exporter/exportLib.py", line 201, in ?
    class ChannelsDumper(BaseSubelementDumper):
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/exporter/exportLib.py", line 203, in ChannelsDumper
    subelement_dumper_class = _ChannelDumper
NameError: name '_ChannelDumper' is not defined