1696777 - fixed su directive
error: skipping "/var/log/rhn/rhn_proxy_broker.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/rhn/rhn_proxy_redirect.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
(cherry picked from commit 72c52def6ecfbcf68d79a49cfb782f886ba3580d)