fixed errata_from export
fixing
Exception type <type 'exceptions.KeyError'>
...
    arr.append(SimpleDumper(self._writer, k, self._row[v] or "", b))
KeyError: 'errata_from'

introduced in 307d2c5606ab10561acbfa3fda89b5c0a2671233