1646942 - openscap rule identifiers can exceed 100 chars
fixing ISE on /rhn/systems/details/audit/ListScap.do
2018-11-06 12:09:29,023 [TP-Processor7] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back javax.el.ELException: Error reading 'diffIcon' on type com.redhat.rhn.frontend.dto.XccdfTestResultDto
...
Caused by:
java.lang.IllegalArgumentException: Multiple rules with idref=xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at_o_...