NVL(int, int) function replaced with COALESCE
We replace all NVL functions that does not operate on varchars.

Plus fix of my previous commit (forgot ON keywords).

2010-10-19 07:32:13,098 [TP-Processor3] ERROR
com.redhat.rhn.frontend.servlets.SessionFilter - Error during
transaction. Rolling back
javax.servlet.ServletException: ERROR: syntax error at or near "OUTER"
    at
org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:535)
    at
org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:433)
    at
org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237)
    at
com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:82)
    at
org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
    at
org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:101)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
    at
com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:67)