do not raise exception in exception in case stream is None
addressing:
Exception Handler Information
Traceback (most recent call last):
  File "/usr/share/rhn/satellite_tools/satsync.py", line 488, in
_process_simple
    self.containerHandler.process(stream)
  File "/usr/share/rhn/satellite_tools/sync_handlers.py", line 501, in
process
    self.handler.process(stream)
  File "/usr/share/rhn/satellite_tools/xmlSource.py", line 137, in process
    stream.close()
AttributeError: 'NoneType' object has no attribute 'close'