618300 - default_db is no longer needed
This is to avoid traceback during osa-dispatcher startup:

Traceback (most recent call last):
  File "/usr/share/rhn/osad/jabber_lib.py", line 119, in main
    self.setup_config(config)
  File "/usr/share/rhn/osad/osa_dispatcher.py", line 81, in setup_config
    rhnSQL.initDB()
  File "/usr/share/rhn/server/rhnSQL/__init__.py", line 119, in initDB
    __init__DB(backend, host, port, username, password, database)
  File "/usr/share/rhn/server/rhnSQL/__init__.py", line 52, in
__init__DB
    __DB.connect()
  File "/usr/share/rhn/server/rhnSQL/driver_cx_Oracle.py", line 385, in
connect
    raise apply(sql_base.SQLConnectError, err_args)
SQLConnectError: (12154, 'ORA-12154: TNS:could not resolve the connect
identifier specified\n', 'oracleinstance', 'Connection_Connect(): server
attach')