removing insert of NULL value(PG)
ERROR:  column "errata_id" is of type numeric but expression is of type text at character
133
HINT:  You will need to rewrite or cast the expression.
STATEMENT:  INSERT INTO rhnServerNeededCache (server_id, errata_id, package_id)
                  ( SELECT /*+ RULE */ DISTINCT
                     S.id as server_id,
                     NULL as errata_id,
                     P.id as package_id
                        FROM
                             rhnPackage P,
                             rhnServerPackageArchCompat SPAC,
                             rhnPackageEVR P_EVR,
                             rhnPackageEVR SP_EVR,
                             rhnServerPackage SP,
                             rhnServerChannel SC,
                             rhnServer S

...