No need to Disconnect, hopefully.
Addressing
ERROR: Spacewalk 1: Cannot generate configuration: RHN::Exception: DBD::Oracle::db set_err failed: Can't disconnect cache-loaded RHN::DB handle