Force EVR to be strings in the backend (PG)
Implicit casts are not the same as on Oracle so we convert EVR to
string explicitely. Resolving

ERROR:  operator does not exist: character varying = integer at character 363
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:
                select
                       c.checksum_type,
                       c.checksum,
                       p.path path
                 from
                       rhnPackageEVR pe,
                       rhnPackageName pn,
                       rhnPackage p,
                       rhnPackageArch pa,
                       rhnChecksumView c
                 where
                       pn.name     = E'huge-rpm'
                  and  ( pe.epoch  = 0 or
                        ( pe.epoch is null and 0 is null )
                       )
                  and  pe.version  = E'1.0'
                  and  pe.release  = E'5'
                  and  ( p.org_id  = 1 or
                        ( p.org_id is null and 1 is null )
                       )
                  and  p.name_id   = pn.id
                  and  p.evr_id    = pe.id
                  and  p.package_arch_id = pa.id
                  and  pa.label    = E'noarch'
                  and  p.checksum_id = c.id
                  and c.checksum = E'8f028f9aabb263a42c99df5fc94ebdc5'
                                                  and c.checksum_type = E'md5'