Sysdate changed to current_timestamp
Exception Handler Information
Traceback (most recent call last):
  File "/usr/share/rhn/server/apacheRequest.py", line 120, in
call_function
    response = apply(func, params)
  File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line
1046, in add_hw_profile
    server = self.auth_system(system_id)
  File "/usr/share/rhn/server/rhnHandler.py", line 65, in auth_system
    server.checkin(check_for_abuse = self.check_for_abuse)
  File "/usr/share/rhn/server/rhnServer/server_class.py", line 755, in
checkin
    check_for_abuse=check_for_abuse)
  File "/usr/share/rhn/server/rhnServer/server_lib.py", line 220, in
checkin
    h.execute(server_id = server_id)
  File "/usr/share/rhn/server/rhnSQL/sql_base.py", line 166, in execute
    return apply(self._execute_wrapper, (self._execute, ) + p, kw)
  File "/usr/share/rhn/server/rhnSQL/driver_postgresql.py", line 256, in
_execute_wrapper
    raise rhnSQL.SQLStatementPrepareError(0, str(e), self.sql)
SQLStatementPrepareError: ('column "sysdate" does not exist at character
45\n', 0, '\n    update rhnServerInfo\n    set checkin = sysdate,
checkin_counter = checkin_counter + 1\n    where server_id =
%(server_id)s\n    ')