1120261 - added code to update-packages to fix changelog encoding
The actual error is thrown by sax xml parser because text in rhn-package-11111.xml.gz
is not valid UTF8. There's no place to fix it in spacewalk code we have to fix the data
before exporting. To fix this error you should run
        update-packages --update-changelog
on exporter machine and create new dump with rhn-satellite-exporter (or resync data with ISS).

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/xmlSource.py", line 131, in process
    self.__parser.parse(self.__stream)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/sax/expatreader.py", line 109, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.6/site-packages/_xmlplus/sax/expatreader.py", line 220, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/xmlSource.py", line 238, in fatalError
    raise FatalParseException(e._msg, e, e._locator)
FatalParseException: /var/satellite/import/base/packages/11/rhn-package-11111.xml.gz:9:1633: not well-formed (invalid token)