rewriting MINUS to OUTER JOIN(PG)
since PG doesn't support 'MINUS' and oracle 'EXCEPT'

addressing:
2010-11-11 04:58:25,425 [TP-Processor2] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: SELECT  CC.id, CC.name
  FROM  rhnConfigChannel CC, rhnConfigChannelType CCT
 WHERE  CC.org_id = ?
   AND  CC.confchan_type_id = CCT.id
   AND  rhn_config_channel.get_user_chan_access(CC.id, ?) = 1
   AND  CCT.label = 'normal'
   AND  CC.id NOT IN ( SELECT XXX.config_channel_id
                         FROM rhnServerConfigChannel XXX
                        WHERE NOT EXISTS ( SELECT RS.element
                                             FROM rhnSet RS
                                            WHERE RS.label = 'system_list'
                                                  MINUS
                                           SELECT SCC.server_id
                                             FROM rhnServerConfigChannel SCC
                                            WHERE SCC.config_channel_id = XXX.config_channel_id ) )
ORDER BY UPPER(CC.name)
com.redhat.rhn.common.db.WrappedSQLException: ERROR: syntax error at or near "MINUS"
    at com.redhat.rhn.common.translation.SqlExceptionTranslator.postgreSqlException(SqlExceptionTranslator.java:56)