just set one required attribute to be compatible with all xmlrpclib versions
fixing exceptions.AttributeError: class Transport has no attribute '__init__' on RHEL 5
see d726a1eac0193bed1b36d84f96b2e54bf9af8d76