Need to stringify the epoch.
Addressing
  File "/usr/lib/python2.4/site-packages/spacewalk/server/apacheRequest.py", line 118, in call_function
    response = apply(func, params)
  File "/usr/share/rhn/server/handlers/app/packages.py", line 305, in channelPackageSubscriptionBySession
    return self._channelPackageSubscription(authobj, info)
  File "/usr/share/rhn/server/handlers/app/packages.py", line 367, in _channelPackageSubscription
    checksum = package['checksum'])
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 166, in execute
    return apply(self._execute_wrapper, (self._execute, ) + p, kw)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 263, in _execute_wrapper
    raise rhnSQL.SQLStatementPrepareError(0, str(e), self.sql)
SQLStatementPrepareError: ('operator does not exist: character varying = integer at character 363
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
', 0, '
        select
               c.checksum_type,
               c.checksum,
               p.path path
         from
               rhnPackageEVR pe,
               rhnPackageName pn,
               rhnPackage p,
               rhnPackageArch pa,
               rhnChecksumView c
         where
               pn.name     = %(pkg_name)s
          and  ( pe.epoch  = %(pkg_epoch)s or
                ( pe.epoch is null and %(pkg_epoch)s is null )
               )
          and  pe.version  = %(pkg_version)s
          and  pe.release  = %(pkg_rel)s
          and  ( p.org_id  = %(orgid)s or
                ( p.org_id is null and %(orgid)s is null )
               )
          and  p.name_id   = pn.id
          and  p.evr_id    = pe.id
          and  p.package_arch_id = pa.id
          and  pa.label    = %(pkg_arch)s
          and  p.checksum_id = c.id
          and c.checksum = %(checksum)s
                                          and c.checksum_type = %(checksum_type)s
    ')