fixed postgresql failure on RHEL6
addressing
ERROR: unhandled exception occurred:
Traceback (most recent call last):
  File "/usr/bin/rhn-satellite-activate", line 43, in <module>
    sys.exit(abs(mod.main() or 0))
  File "/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/rhn_satellite_activate.py", line 584, in main
    username=db_user, password=db_password, database=database)
  File "/usr/lib/python2.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 121, in initDB
    __init__DB(backend, host, port, username, password, database)
  File "/usr/lib/python2.6/site-packages/spacewalk/server/rhnSQL/__init__.py", line 52, in __init__DB
    __DB.connect()
  File "/usr/lib/python2.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 169, in connect
    return self.connect(reconnect=0)
  File "/usr/lib/python2.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 174, in connect
    [self.database, e.pgcode, e.pgerror, "Attempting Re-Connect to the database failed",])
AttributeError: 'exceptions.AttributeError' object has no attribute 'pgcode'
(cherry picked from commit e5cb31a510d620e05509da7f50634aa0a3798989)