698567 - give the transaction that we have to use to read the file header a sandbox database.
Ever since we've prevented Spacewalk from reading the rpm database
with SELinux, it complains in the error_log:

    error: cannot open Packages database in /var/lib/rpm

This workaround should give it a place to create its own database.