add BuildRequires: python-hashlib
we now run test during builds, so we need BuildRequires: python-hashlib
addressing:
  File "/usr/lib/python2.4/site-packages/spacewalk/common/checksum.py", line 22, in ?
ImportError: No module named Crypto.Hash

additionaly if we build on el4 where is not hashlib we have to require python-crypto