use parent class SQLException instead of PSQLException
additionaly loading org.postgresql.util.PSQLException will fail if we have Oracle backand
in such case pg module is not present and will fail with traceback

INFO   | jvm 1    | 2010/04/07 15:52:08 | Exception in thread "Thread-11" java.lang.NoClassDefFoundError: org/postgresql/util/PSQLException
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at com.redhat.rhn.common.db.NamedPreparedStatement.execute(NamedPreparedStatement.java:140)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:454)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:431)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at com.redhat.rhn.common.db.datasource.CachedStatement.executeUpdate(CachedStatement.java:269)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at com.redhat.rhn.common.db.datasource.WriteMode.executeUpdate(WriteMode.java:33)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at com.redhat.rhn.taskomatic.task.errata.ErrataQueueWorker.run(ErrataQueueWorker.java:98)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:761)
INFO   | jvm 1    | 2010/04/07 15:52:08 |       at java.lang.Thread.run(Thread.java:636)