fixed satellite-sync (reverted checksum changes in blacklistImport)
Traceback (most recent call last):
  File "/usr/share/rhn/satellite_tools/xmlSource.py", line 132, in process
    self.__parser.parse(self.__stream)
  File "/usr/lib64/python2.4/site-packages/_xmlplus/sax/expatreader.py", line 109, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.4/site-packages/_xmlplus/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.4/site-packages/_xmlplus/sax/expatreader.py", line 216, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.4/site-packages/_xmlplus/sax/expatreader.py", line 314, in
+end_element
    self._cont_handler.endElement(name)
  File "/usr/share/rhn/satellite_tools/xmlSource.py", line 225, in endElement
    self.__container.endElement(element)
  File "/usr/share/rhn/satellite_tools/xmlSource.py", line 800, in endElement
    self.endContainerCallback()
  File "/usr/share/rhn/satellite_tools/diskImportLib.py", line 283, in endContainerCallback
    importer.run()
  File "/usr/share/rhn/server/importlib/importLib.py", line 627, in run
    self.fix()
  File "/usr/share/rhn/server/importlib/blacklistImport.py", line 49, in fix
    entry['checksum_id'] = self.checksums[entry['checksum']]
  File "/usr/lib64/python2.4/UserDict.py", line 17, in __getitem__
    def __getitem__(self, key): return self.data[key]
KeyError: 'checksum'