Use current_timestamp instead of sysdate.
Addressing
2010/12/21 14:17:30 -04:00 25858 0.0.0.0: osad/jabber_lib.main('ERROR', 'Traceback (most recent call last):
  File "/usr/share/rhn/osad/jabber_lib.py", line 121, in main
    self.process_forever(c)
  File "/usr/share/rhn/osad/jabber_lib.py", line 179, in process_forever
    self.process_once(client)
  File "/usr/share/rhn/osad/osa_dispatcher.py", line 146, in process_once
    self.reap_pinged_clients()
  File "/usr/share/rhn/osad/osa_dispatcher.py", line 185, in reap_pinged_clients
    ret = h.execute(online_id=online_id, offline_id=offline_id)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 166, in execute
    return apply(self._execute_wrapper, (self._execute, ) + p, kw)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 263, in _execute_wrapper
    raise rhnSQL.SQLStatementPrepareError(0, str(e), self.sql)
SQLStatementPrepareError: (\'column "sysdate" does not exist at character 144\
\', 0, \'\
        update rhnPushClient\
           set state_id = %(offline_id)s\
         where state_id = %(online_id)s\
           and last_ping_time is not null\
           and sysdate > next_action_time\
    \')
')