fix configchannel export - do not create 'contents' key for directories
Import a directory which has a 'contents' key failed with

InvalidArgsException: Invalid argument(s): contents