IPv6: filter out params, which are not used in query
addressing:
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/spacewalk/server/apacheRequest.py", line 123, in call_function
    response = apply(func, params)
  File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line 999, in refresh_hw_profile
    server.save_hardware()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_wrapper.py", line 90, in save_hardware
    ret = self.save_hardware_byid(self.server["id"])
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 917, in save_hardware_byid
    hw.save(sysid)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 473, in save
    info['ipv6'].save(self.get_server_id(server_id, name))
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 635, in save
    self._delete(deletes)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 657, in _delete
    return _dml(h, params)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 742, in _dml
    rowcount = apply(statement.executemany, (), params)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 172, in executemany
    return apply(self._execute_wrapper, (self._executemany, ) + p, kw)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_cx_Oracle.py", line 108, in _execute_wrapper
    retval = apply(function, p, kw)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_cx_Oracle.py", line 208, in _executemany
    self._real_cursor.executemany(None, arr)
SQLError: (1036, 'ORA-01036: illegal variable name/number\n', 'delete from rhnServerNetAddress6 where interface_id =
+:interface_id and address = :address and scope = :scope')