Casting the user id to string to make rhn_install_org_satellites happy.
Addressing
ERROR: function rhn_install_org_satellites(bigint, bigint, bigint) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
        at com.redhat.rhn.common.translation.SqlExceptionTranslator.postgreSqlException(SqlExceptionTranslator.java:56)
        at com.redhat.rhn.common.translation.SqlExceptionTranslator.sqlException(SqlExceptionTranslator.java:45)
        at com.redhat.rhn.common.db.NamedPreparedStatement.execute(NamedPreparedStatement.java:118)
        at com.redhat.rhn.common.db.datasource.CachedStatement.executeCallable(CachedStatement.java:511)
        at com.redhat.rhn.common.db.datasource.CallableMode.execute(CallableMode.java:34)
        at com.redhat.rhn.manager.monitoring.ScoutConfigPushCommand.store(ScoutConfigPushCommand.java:60)
        at com.redhat.rhn.frontend.action.systems.entitlements.SystemEntitlementsSubmitAction.operateAddOnEntitlements(SystemEntitlementsSubmitAction.java:412)
        at com.redhat.rhn.frontend.action.systems.entitlements.SystemEntitlementsSubmitAction.processAdd(SystemEntitlementsSubmitAction.java:281)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:269)
        at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:170)
        at org.apache.struts.actions.LookupDispatchAction.execute(LookupDispatchAction.java:146)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)