fixed clear_subscriptions() call with optional parameters
fixing
javax.servlet.ServletException: com.redhat.rhn.common.db.WrappedSQLException: ERROR: fun
ction rhn_channel.clear_subscriptions(numeric, integer) is not unique
  Hint: Could not choose a best candidate function. You might need to add explicit type
casts.
  Where: PL/pgSQL function "delete_server" line 79 at PERFORM