Fix `rhncfg-client verify' traceback for missing symlinks
Traceback (most recent call last):
  File "/usr/bin/rhncfg-client", line 34, in <module>
    sys.exit(Main().main() or 0)
  File "/usr/share/rhn/config_common/rhn_main.py", line 187, in main
    handler.run()
  File "/usr/share/rhn/config_client/rhncfgcli_verify.py", line 83, in run
    ret_dict = self._process_file(src, dst, file, ftype, file_info)
  File "/usr/share/rhn/config_client/rhncfgcli_verify.py", line 251, in _process_file
    dst_selinux = lgetfilecon(dst)[1]
OSError: [Errno 2] No such file or directory