fix delete user by deleting the reference to rhnResetPassword
Delete a normal user result in

 ERROR:  -20255 : (cannot_delete_user) - The specified user may not be deleted.

calling "delete from web_contact where id = <NUM>" directly result in:

 ERROR:  update or delete on table "web_contact" violates foreign key constraint "rhn_rstpwd_uid_fk" on table "rhnresetpassword"
 DETAIL:  Key (id)=(3) is still referenced from table "rhnresetpassword".

(cherry picked from commit 7a47296d12dfd2745eeec884abddab21cc924823)