The web_product_valid_numbers table does not exist in Spacewalk 0.7 / Satellite 5.3.
Thus, we delete functions that might ever think of touching
it eventually.

Even if we managed to invoke the validate_reg_num on the server,
it would fail with:

Exception Handler Information
Traceback (most recent call last):
  File "/usr/share/rhn/server/apacheRequest.py", line 120, in call_function
    response = apply(func, params)
  File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line 1187, in validate_reg_num
    code = ValidNumber(prodcode)
  File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line 81, in ValidNumber
    h.execute(regnum = reg_num)
  File "/usr/share/rhn/server/rhnSQL/sql_base.py", line 161, in execute
    return apply(self._execute_wrapper, (self._execute, ) + p, kw)
  File "/usr/share/rhn/server/rhnSQL/driver_cx_Oracle.py", line 107, in _execute_wrapper
    raise apply(sql_base.SQLStatementPrepareError, args)
SQLStatementPrepareError: ('ORA-00942: table or view does not exist\n', 942, 'select registered_flag flag from web_product_valid_numbers where reg_number = :regnum')