Upon drop, the default must not be specified.
Addressing
ERROR:  syntax error at or near "default"
LINE 6:                update_family_countsYN in numeric default 1 ...