Do not parse the command line options, there are none.
Addressing
  File "/usr/bin/rhn-schema-version", line 58, in processCommandline
    return options
NameError: global name 'options' is not defined