require rhnlib with IDN stuff
fixing
Traceback (most recent call last):
  File "/usr/share/yum-plugins/rhnplugin.py", line 34, in ?
    import up2date_client.up2dateAuth as up2dateAuth
  File "/usr/share/rhn/up2date_client/up2dateAuth.py", line 4, in ?
    import rhnserver
  File "/usr/share/rhn/up2date_client/rhnserver.py", line 21, in ?
    import rpcServer
  File "/usr/share/rhn/up2date_client/rpcServer.py", line 6, in ?
    import config
  File "/usr/share/rhn/up2date_client/config.py", line 17, in ?
    from rhn.connections import idn_ascii_to_pune, idn_pune_to_unicode
ImportError: cannot import name idn_ascii_to_pune