export from hosted does not know soft dependecies
addressing:
Exception Handler Information
Traceback (most recent call last):
  File "/usr/bin/satellite-sync", line 139, in main
    return satsync.Runner().main()
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 226, in main
    ret = method()
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 340, in _step_packages
    self._affected_channels = self.syncer.import_packages()
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 1595, in import_packages
    [sources])
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 1569, in _proces_batch
    prompt, nevermorethan, process_function_args)
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 1549, in _processWithProgressBar
    process_function(chunk, *process_function_args)
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 1576, in _import_packages_process
    sync_handlers.import_packages(batch, sources)
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/sync_handlers.py", line 378, in import_packages
    importer.run()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/importlib/importLib.py", line 623, in run
    self.preprocess()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/importlib/packageImport.py", line 58, in preprocess
    self._processPackage(package)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/importlib/packageImport.py", line 223, in _processPackage
    if type(package[tag]) != type([]):
  File "/usr/lib64/python2.4/UserDict.py", line 17, in __getitem__
    def __getitem__(self, key): return self.data[key]
KeyError: 'recommends'