postgresql doesn't understand for update of column (PG)
fixing
ERROR:  relation "contents" in FOR UPDATE/SHARE clause not found
in FROM clause at character 107