Fixing typo; also making the nextval call hopefully faster by not going to SQL.
Addressing
<rhnFault class (code = 54, text = '0')>
(54, '0', '\n     Package Upload Failed due to uniqueness constraint violation.\n     Make sure the package does not have any duplicate dependencies
or\n     does not already exists on the server\n     ')

and

ERROR:  record "new" has no field "is"
CONTEXT:  PL/pgSQL function "rhn_package_changelog_id_trig_fun" line 2 at IF