Using password_in for parameter name to avoid confusion.
Addressing
File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 283, in _execute_
    self._real_cursor.execute(self.sql, params)
SQLStatementPrepareError: (\'syntax error at or near "$1" at character 78
QUERY:  insert into rhnPushDispatcher (id, jabber_id, last_checkin, hostname, port,  $1 ) values (sequence_nextval(\\\'rhn_pushdispatch_id_seq\\\'),  $2 , current_timestamp,  $3 ,  $4 ,  $1 )
CONTEXT:  SQL statement in PL/PgSQL function "rhn_asdf_03139246e715360fa7b1c85c7b9978d72cedccd8" near line 15
\', 0, "create function rhn_asdf_03139246e715360fa7b1c85c7b9978d72cedccd8 (hostname_in varchar,port_in numeric,jabber_id_in varchar,password varchar) returns void as $x03139246e715360fa7b1c85c7b9978d72cedccd8$
        declare
            i numeric;
        begin
            update rhnPushDispatcher
               set last_checkin = current_timestamp,
                   hostname = hostname_in,
                   port = port_in
             where jabber_id = jabber_id_in
            returning id into i;
            if i is null then
                -- Have to insert the row
                insert into rhnPushDispatcher
                       (id, jabber_id, last_checkin, hostname, port, password)
                values (sequence_nextval(\'rhn_pushdispatch_id_seq\'), jabber_id_in, current_timestamp,
                       hostname_in, port_in, password);
            end if;
        end;
    $x03139246e715360fa7b1c85c7b9978d72cedccd8$ language plpgsql")
')