Do not import yum on Debian platform
Addressing:
Traceback (most recent call last):
  File /usr/lib/apt-spacewalk/pre_invoke.py, line 24, in <module>
    from up2date_client import rhnChannel
  File /usr/share/rhn/up2date_client/rhnChannel.py, line 5, in <module>
    import up2dateAuth
  File /usr/share/rhn/up2date_client/up2dateAuth.py, line 4, in <module>
    import rhnserver
  File /usr/share/rhn/up2date_client/rhnserver.py, line 21, in <module>
    import rpcServer
  File /usr/share/rhn/up2date_client/rpcServer.py, line 12, in <module>
    import clientCaps
  File /usr/share/rhn/up2date_client/clientCaps.py, line 10, in <module>
    from capabilities import parseCap
  File /usr/share/rhn/up2date_client/capabilities.py, line 4, in <module>
    import up2dateErrors
  File /usr/share/rhn/up2date_client/up2dateErrors.py, line 16, in <module>
    from yum.Errors import RepoError
ImportError: No module named yum.Errors
E: Problem executing scripts APT::Update::Pre-Invoke '/usr/lib/apt-spacewalk/pre_invoke.py'
E: Sub-process returned an error code

Introduced by: 3ef12a289c1f1341144caf2af1d2595cd1500a66