Correcting NULL values in channel manager repo gen (PG)
Addressing

ERROR:  new row for relation "rhnreporegenqueue" violates check constraint "vn_rhnreporegenqueue_reason"
STATEMENT:  INSERT
          INTO rhnRepoRegenQueue
                (id, channel_label, client, reason, force, bypass_filters, next_action, created, modified)
        VALUES (null,                   -- the id is set by trigger on rhnRepoRegenQueue
                $1, $2, $3, 'N', 'N', current_timestamp, current_timestamp, current_timestamp)