spacecmd: Check number of arguments in system_show_packageversion
Fix the following error:

spacecmd {SSM:0}> system_show_packageversion
ERROR: list index out of range
spacecmd {SSM:0}>

system_show_packageversion requires exactly two arguments, so add a
check that shows usage msg if a different number of arguments was passed
- just like with all the other commands.

Signed-off-by: Jakub Jankowski <shasta@toxcorp.com>