include Base64 from gpache.commons.codec.binary
not from com.sun.org.apache.xml.internal.security.utils

adressing:
    [javac] /builddir/build/BUILD/spacewalk-java-1.7.8/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ConfigRevisionSerializer.java:22: package com.sun.org.apache.xml.internal.security.utils does not exist
    [javac] import com.sun.org.apache.xml.internal.security.utils.Base64;
    [javac]                                                      ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.7.8/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ConfigRevisionSerializer.java:152: cannot find symbol
    [javac] symbol  : variable Base64
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.serializer.ConfigRevisionSerializer
    [javac]         helper.add(CONTENTS, Base64.encode(content.getBytes()));
    [javac]                              ^