Since RHN::DB sets FetchHashKeyName to NAME_uc and monitoring now uses RHN::DB, the column name is now uppercase.
Addressing
ERROR: Spacewalk 1: Cannot generate configuration: Message SatClusterRecord::get_physical_location_name() not understood

TRACEBACK:
 at /usr/lib/perl5/vendor_perl/5.8.8/NOCpulse/Object.pm line 443
	NOCpulse::Object::doesNotUnderstand('SatClusterRecord=HASH(0x2aae515d6fc0)', 'SatClusterRecord', 'get_physical_location_name') called at /usr/lib/perl5/vendor_perl/5.8.8/NOCpulse/Object.pm line 463
	NOCpulse::Object::AUTOLOAD('SatClusterRecord=HASH(0x2aae515d6fc0)') called at /usr/lib/perl5/vendor_perl/5.8.8/NOCpulse/SatConfig/GenerateConfig.pm line 44
	eval {...} called at /usr/lib/perl5/vendor_perl/5.8.8/NOCpulse/SatConfig/GenerateConfig.pm line 19
	NOCpulse::SatConfig::GenerateConfig::handler('Apache2::RequestRec=SCALAR(0x2aae5a006a50)') called at -e line 0
	eval {...} called at -e line 0