Need to avoid inserting empty strings, we use NULL (None) instead.
Addressing
psycopg2.IntegrityError: new row for relation "rhnreporegenqueue" violates check constraint "vn_rhnreporegenqueue_reason"