Array concatenation seems to want array_append.
Addressing
ProgrammingError: ERROR:  operator is not unique: character varying[] || unknown
LINE 1: SELECT   $1  || 'rhn_virtualization_platform'
                     ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
QUERY:  SELECT   $1  || 'rhn_virtualization_platform'
CONTEXT:  PL/pgSQL function "modify_org_service" line 65 at assignment