require higher version for checkstyle
fixes
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser
        at com.puppycrawl.tools.checkstyle.Main.parseCli(Main.java:159)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:96)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.DefaultParser

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/ArrayUtils
        at com.puppycrawl.tools.checkstyle.Checker.<init>(Checker.java:98)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:266)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.ArrayUtils