workaround yum.update_md.UpdateNotice, which in rhel5 does not have __setitem__
addressing:
...
Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 69, in ?
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 63, in main
    sync.main()
  File
"/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/reposync.py", line
110, in main
    self.import_updates(plugin, url)
  File
"/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/reposync.py", line
145, in import_updates
    self.upload_updates(notices)
  File
"/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/reposync.py", line
159, in upload_updates
    notice = self.fix_notice(notice)
  File
"/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/reposync.py", line
453, in fix_notice
    notice['version'] = new_version / 100
TypeError: object does not support item assignment