532145 - define local variable ipaddr before it is used
addressing:
Traceback (most recent call last):
      File "/usr/share/rhn/up2date_client/rhnregGui.py", line 949, in
populateProfile
        if ipaddr:
    exceptions.UnboundLocalError: local variable ipaddr referenced before
assignment