Added update_neede_cache to Postgresql rhn_server.pkb
Exception Handler Information
Traceback (most recent call last):
  File "/usr/share/rhn/server/apacheRequest.py", line 120, in
call_function
    response = apply(func, params)
  File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line
906, in add_packages
    server.save_packages()
  File "/usr/share/rhn/server/rhnServer/server_wrapper.py", line 73, in
save_packages
    ret = self.save_packages_byid(self.server["id"], schedule=schedule)
  File "/usr/share/rhn/server/rhnServer/server_packages.py", line 236,
in save_packages_byid
    update_errata_cache(sysid)
  File "/usr/share/rhn/server/rhnServer/server_packages.py", line 316,
in update_errata_cache
    update_needed_cache(server_id)
  File "/usr/share/rhn/server/rhnSQL/driver_postgresql.py", line 107, in
__call__
    result = Function.__call__(self, *args)
  File "/usr/share/rhn/server/rhnSQL/driver_postgresql.py", line 90, in
__call__
    return self.cursor.execute(query, new_args)
ProgrammingError: function rhn_server.update_needed_cache(integer) does
not exist at character 8
HINT:  No function matches the given name and argument types. You might
need to add explicit type casts.