fix perrmissions on /usr/share/spacewalk/taskomatic/*.jar
fixing
Error: Transaction check error:
  file /usr/share/spacewalk/taskomatic/ojdbc14.jar conflicts between attempted installs of spacewalk-taskomatic-2.7.42-1.fc24.noarch and spacewalk-java-oracle-2.7.42-1.fc24.noarch
  file /usr/share/spacewalk/taskomatic/quartz-oracle.jar conflicts between attempted installs of spacewalk-taskomatic-2.7.42-1.fc24.noarch and spacewalk-java-oracle-2.7.42-1.fc24.noarch