495778 - process UTF-8 input.
Addressing
Exception Handler Information
Traceback (most recent call last):
  File "/usr/share/rhn/server/apacheUploadServer.py", line 107, in _wrapper
    ret = function(req)
  File "/usr/share/rhn/upload_server/handlers/package_push/package_push.py", line 145, in handler
    relative_path=self.rel_package_path, org_id=self.org_id)
  File "/usr/share/rhn/server/rhnPackageUpload.py", line 223, in push_package
    header_end=header_end, channels=channels)
  File "/usr/share/rhn/server/importlib/mpmSource.py", line 215, in create_package
    org_id=org_id, channels=channels)
  File "/usr/share/rhn/server/importlib/mpmSource.py", line 88, in populate
    org_id, channels)
  File "/usr/share/rhn/server/importlib/headerSource.py", line 135, in populate
    header_start, header_end)
  File "/usr/share/rhn/server/importlib/headerSource.py", line 57, in populate
    val = str(val)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 4: ordinal not in range(128)
(cherry picked from commit 8803cf9c8ac68f2a3146af2086d20689ab2611d6)