fix rhnConfig namespace
addressing:
AttributeError: 'module' object has no attribute 'rhnConfig'
(cherry picked from commit a6c713ff67a630b2be194e9a9b87c01b7727ee75)