Fixed rhnServerOverview VIEW to return numeric
In PostgreSQL the 1 or 0 constants are INTEGER and not NUMERIC (NUMBER
in Oracle). We need to add explicit casts to all places where we
directly return some numeric constant and expect NUMERIC/NUMBER in the
UI (mapped to Long in Java).

2010-10-18 10:24:03,522 [TP-Processor8] ERROR
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/rhn].[action]
- Servlet.service() for servlet action threw exception
com.redhat.rhn.common.util.MethodNotFoundException: Could not find
method called: setLocked in class:
com.redhat.rhn.frontend.dto.SystemOverview with params: [type:
java.lang.Integer, value: 0]
    at
com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:196)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:754)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:604)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:462)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:371)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:406)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.executeElaborator(CachedStatement.java:352)
    at
com.redhat.rhn.common.db.datasource.SelectMode.elaborate(SelectMode.java:159)
    at
com.redhat.rhn.common.db.datasource.ModeElaborator.elaborate(ModeElaborator.java:44)
    at
com.redhat.rhn.frontend.taglibs.list.decorators.ElaborationDecorator.elaborateContents(ElaborationDecorator.java:57)
    at
com.redhat.rhn.frontend.taglibs.list.decorators.ElaborationDecorator.setCurrentList(ElaborationDecorator.java:37)
    at
com.redhat.rhn.frontend.taglibs.list.ListTag.doAfterBody(ListTag.java:466)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspx_meth_rl_005flist_005f0(Unknown
Source)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspx_meth_c_005fif_005f0(Unknown
Source)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspx_meth_rl_005flistset_005f0(Unknown
Source)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspService(Unknown
Source)
    at
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:98)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:691)
    at
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469)
    at
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:403)
    at
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:301)
    at
org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1085)
    at
org.apache.struts.action.RequestProcessor.processForwardConfig(RequestProcessor.java:398)
    at
org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:241)
    at
com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:82)
    at
org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
    at
org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:101)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
    at
com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:67)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:108)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:210)
    at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:172)
    at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)