1696777 - fixed file mode
error: Ignoring rhn-proxy-broker because of bad file mode - must be 0644 or 0444.
error: Ignoring rhn-proxy-redirect because of bad file mode - must be 0644 or 0444.
(cherry picked from commit bab0a6fe73ac9c53f7a174c7f6eeb35fb33caab4)