651857 - removing forgotten lines, which makes no sense and cause TB
addressing:
Traceback (most recent call last):
  File "/usr/sbin/rhn-channel", line 92, in ?
    main()
  File "/usr/sbin/rhn-channel", line 86, in main
    s = rhnserver.RhnServer()
NameError: global name 'rhnserver' is not defined