Keyword MINUS is not recognized by PostgreSQL
Changing to ANSI syntax for PG. We do have only three occurances of
the MINUS keyword.

Resolving

ERROR:  syntax error at or near "MINUS" at character 204
STATEMENT:
                            select cp.package_id id
                from rhnChannel c, rhnChannelPackage cp
                where c.label  in (E'psklenar-consider-all-31680-14473')
                and cp.channel_id = c.id
                    MINUS
                            select cp.package_id id
                from rhnChannel c, rhnChannelPackage cp
                where c.label not in (E'psklenar-consider-all-31680-14473')
                and cp.channel_id = c.id