requre quartz version lower than 2.0
due to compatibiliuty issues like:
jvm 1    | org.quartz.Scheduler.addTriggerListener(Lorg/quartz/TriggerListener;)V
java.lang.NoSuchMethodError: org.quartz.Scheduler.addTriggerListener(Lorg/quartz/TriggerListener;)V
at com.redhat.rhn.taskomatic.core.SchedulerKernel.<init>(SchedulerKernel.java:130)