add perl-Mail-RFC822-Address to RHEL7 repo
fixing
Error: Package: spacewalk-base-2.3.4-1.el7.noarch (spacewalk-nightly)
           Requires: perl(Mail::RFC822::Address)