Added setHasSubscription for Integer (PostgreSQL)
The default type for constatnt numbers in PostgreSQL is INTEGER (Integer
in Java mapping). In Oracle this is NUMBER (Long in Java).

We need to create overriden setter methods for all data objects in Java
that operates on views returning INTEGERs.

com.redhat.rhn.common.util.MethodNotFoundException: Could not find
method called: setHasSubscription in class:
com.redhat.rhn.frontend.dto.ChannelOverview with params: [type:
java.lang.Integer, value: 1]
    at
com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:196)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:754)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:604)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:462)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:432)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:336)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:341)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:281)
    at
com.redhat.rhn.common.db.datasource.SelectMode.execute(SelectMode.java:105)
    at
com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:57)
    at
com.redhat.rhn.manager.channel.ChannelManager.entitlements(ChannelManager.java:228)
    at
com.redhat.rhn.frontend.action.channel.ChannelEntitlementSetupAction.getResult(ChannelEntitlementSetupAction.java:64)
    at
com.redhat.rhn.frontend.taglibs.list.helper.ListHelper.setupDataSet(ListHelper.java:107)
    at
com.redhat.rhn.frontend.taglibs.list.helper.ListHelper.execute(ListHelper.java:100)
    at
com.redhat.rhn.frontend.action.channel.ChannelEntitlementSetupAction.execute(ChannelEntitlementSetupAction.java:53)
    at
org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
    at
org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237)
    at
com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:82)
    at
org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
    at
org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)