require  en (UTF8) locales
fixes
  [javadoc] /builddir/build/BUILD/sitemesh-2.4.2/src/java/com/opensymphony/module/sitemesh/util/FastByteArrayOutputStream.java:24: error: unmappable character for encoding ASCII
  [javadoc]  * @author Rickard ???berg
  [javadoc]                    ^
  [javadoc] /builddir/build/BUILD/sitemesh-2.4.2/src/java/com/opensymphony/module/sitemesh/util/FastByteArrayOutputStream.java:24: error: unmappable character for encoding ASCII
  [javadoc]  * @author Rickard ???berg
  [javadoc]                     ^
  [javadoc] /builddir/build/BUILD/sitemesh-2.4.2/src/java/com/opensymphony/module/sitemesh/util/FastByteArrayOutputStream.java:24: error: unmappable character for encoding ASCII
  [javadoc]  * @author Rickard ???berg
  [javadoc]                      ^
  [javadoc] 3 errors