Correcting spec for spacewalk-java (JAR symlinks).
We were including all files from WEB-INF/lib directory including both
JDBC drivers (Oracle, PostgreSQL). It turned out recent versions of
Tomcat 6 is not able to start when there are broken symbolic links
present in this directory.

We now distribute without these symbolic links. These are part of
spacewalk-java subpackages. Resolving issue:

SEVERE: Error deploying configuration descriptor rhn.xml
java.lang.IllegalStateException: ContainerBase.addChild: start:
LifecycleException:  start: :  java.io.IOException: Failed to access resource
/WEB-INF/lib/postgresql-jdbc.jar
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:795)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
        at org.apache.catalina.core.StandardService.start(StandardService.java:519)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57