spacewalk-java.spec now check for spelling errors. See bellow:
I have just modified the pacewalk-java.spec to check for spelling errors
in all java resources for English (XML files).

Please note if spelling error is found the build will *FAIL*. Yes,
correct. This was upon Jan P request so don't blame me :-)

You will probably need to edit the file scripts/spelling/ignore_en.txt
from time to time by appending all unknown words. The script prints all
words out in the correct form so its easy to append it. Example output
follows:

...

en_US in java/code/src/com/redhat/rhn/frontend/strings/database:
en_US in java/code/src/com/redhat/rhn/frontend/strings/java:
en_US in java/code/src/com/redhat/rhn/frontend/strings/jsp:
sysprefs
Spaecewalk
en_US in java/code/src/com/redhat/rhn/frontend/strings/nav:
en_US in java/code/src/com/redhat/rhn/frontend/strings/template:
ERROR: There are spelling errors in resources, please fix or
add the following words in the scripts/spelling/ignore_en.txt:
--cut--
sysprefs
Spaecewalk
--cut--

...