Adding missing AS keyword to SELECT clause (PG)
Resolving

ERROR:  syntax error at or near "role" at character 31
STATEMENT:
                    select ugt.label role
                      from rhnUserGroup ug,
                           rhnUserGroupType ugt,
                           rhnUserGroupMembers ugm
                     where ugm.user_id = 1
                       and ugm.user_group_id = ug.id
                       and ug.group_type = ugt.id