Default number in Postgresql views is int8 now
Postgresql's default type for numbers is int4 but our code expects int8
(big int). To be precise our java code expects something that is mapped
to java type Long. In Postgresql this is int8 (or big int).

We had three views with column NOTE_COUNT that had int4 which caused
java errors because expected type was Long and not Integer. I have fixed
that.

com.redhat.rhn.common.util.MethodNotFoundException: Could not find
method called: setNoteCount in class:
com.redhat.rhn.frontend.dto.SystemOverview with params: [type:
java.lang.Integer, value: 0]
    at
com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:196)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:754)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:604)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:462)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:371)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:406)
    at
com.redhat.rhn.common.db.datasource.CachedStatement.executeElaborator(CachedStatement.java:352)
    at
com.redhat.rhn.common.db.datasource.SelectMode.elaborate(SelectMode.java:159)
    at
com.redhat.rhn.common.db.datasource.ModeElaborator.elaborate(ModeElaborator.java:44)
    at
com.redhat.rhn.frontend.taglibs.list.decorators.ElaborationDecorator.elaborateContents(ElaborationDecorator.java:57)
    at
com.redhat.rhn.frontend.taglibs.list.decorators.ElaborationDecorator.setCurrentList(ElaborationDecorator.java:37)
    at
com.redhat.rhn.frontend.taglibs.list.ListTag.doAfterBody(ListTag.java:466)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspx_meth_rl_005flist_005f0(Unknown
Source)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspx_meth_c_005fif_005f0(Unknown
Source)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspx_meth_rl_005flistset_005f0(Unknown
Source)
    at
org.apache.jsp.WEB_002dINF.pages.systems.overview_jsp._jspService(Unknown
Source)
    at
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:98)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:691)
    at
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469)
    at
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:403)
    at
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:301)
    at
org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1085)
    at
org.apache.struts.action.RequestProcessor.processForwardConfig(RequestProcessor.java:398)
    at
org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:241)
    at
com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:82)
    at
org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
    at
org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:101)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
    at
com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:67)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:108)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:210)
    at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:172)
    at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
    at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
    at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
    at
org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:200)
    at
org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
    at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:775)