666939 - Insert current_timestamp instead of sysdate
addressing:
Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 69, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 63, in main
    sync.main()
  File
"/usr/lib/python2.7/site-packages/spacewalk/satellite_tools/reposync.py", line
104, in main
    taskomatic.add_to_erratacache_queue(self.channel_label)
  File "/usr/lib/python2.7/site-packages/spacewalk/server/taskomatic.py", line
79, in add_to_erratacache_queue
    h.execute(label=channel, priority=priority)
  File "/usr/lib/python2.7/site-packages/spacewalk/server/rhnSQL/sql_base.py",
line 163, in execute
    return apply(self._execute_wrapper, (self._execute, ) + p, kw)
  File
"/usr/lib/python2.7/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py",
line 263, in _execute_wrapper
    raise rhnSQL.SQLStatementPrepareError(0, str(e), self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('column "sysdate"
does not exist\nLINE 8:                   sysdate\n
^\n', 0, "\n    insert into rhnTaskQueue\n           (org_id, task_name,
task_data, priority, earliest)\n           select coalesce(c.org_id, 1),\n
            'update_errata_cache_by_channel',\n                  c.id,\n
          %(priority)s,\n                  sysdate\n             from
rhnChannel c\n            where c.label = %(label)s\n    ")