958654 - Use different listSetName for the XccdfDetail page.
The list on XccdfDetails page does not have any elaborator
and the list allows the export to CSV. However, when there
was another page with the same listSetName and this page
had bound elaborator to this name --> Our CSV export will
try to evaluate this elaborator.

Such bug may easily remain unnoticed, as the majority of
elaborators use the 'id' attribute. Unfortunatelly, this
one used 'xid'.

Addressing:
com.redhat.rhn.common.db.datasource.MapColumnNotFoundException: Column, xid, not found in driving query results
	at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:391)
	at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaborator(CachedStatement.java:363)
	at com.redhat.rhn.common.db.datasource.SelectMode.elaborate(SelectMode.java:164)
	at com.redhat.rhn.common.db.datasource.ModeElaborator.elaborate(ModeElaborator.java:48)
	at com.redhat.rhn.frontend.action.CSVDownloadAction.getStreamInfo(CSVDownloadAction.java:201)
	at org.apache.struts.actions.DownloadAction.execute(DownloadAction.java:104)
	at com.redhat.rhn.frontend.action.CSVDownloadAction.execute(CSVDownloadAction.java:66)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)