convert empty string to null for DMI values
Prevent:
IntegrityError: new row for relation "rhnserverdmi" violates
                check constraint "vn_rhnserverdmi_product"

(cherry picked from commit b14b1a78521a18777ddfb29e3219748a3f164326)