add missing function to pg Cursor
addressing:
Traceback (most recent call last):
  File "/usr/bin/spacewalk-data-fsck", line 267, in ?
    exit_value += check_db_vs_disk(options)
  File "/usr/bin/spacewalk-data-fsck", line 105, in check_db_vs_disk
    h.close()
AttributeError: Cursor instance has no attribute 'close'

In Oracle the h has value:
<__builtin__.OracleCursor on <cx_Oracle.Connection to spacewalk@//localhost:1521/XE>>

I'm not really sure if we should do something here, but this should be
enough for now.