Do not fail import on ignored errata
When a errata is ignored, because a newer errata has already
been found, this breaks the import with error

ERROR: 'list' object has no attribute 'keys'

because 'packages' of an ignored errata has not been 'transferred'
to a dict() by '_fix_erratum_packages_lookup'