820862 - fix traceback on a fat rhev-3 host
This is to fix the following traceback:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.6/trace.py", line 823, in <module>
    main()
  File "/usr/lib64/python2.6/trace.py", line 811, in main
    t.runctx(code, globs, globs)
  File "/usr/lib64/python2.6/trace.py", line 512, in runctx
    exec cmd in globals, locals
  File "/usr/share/rhn/virtualization/poller.py", line 290, in <module>
    domain_list = poll_through_vdsm()
  File "/usr/share/rhn/virtualization/poller.py", line 140, in poll_through_vdsm
    import localvdsm
  File "/usr/share/rhn/virtualization/localvdsm.py", line 35, in <module>
    raise ImportError('local vdsm not found')

Running
    python /usr/share/rhn/virtualization/poller.py
from cron job would automatically add /usr/share/rhn/virtualization into
python's sys.path. vdsm's config.py imports constants.py but will get
incorrect (i.e. rhn-virtualization's) constants.py, hence the tb above
(the actual exception in fact is:
File "/usr/share/vdsm/config.py", line 67, in <module>
AttributeError: 'module' object has no attribute 'P_TRUSTSTORE'
).

We'll resolve the problem with:
1. Running the poller.py from cron using shell redirection
2. We won't be using (not even packaging) localvdsm.py on rhel-6 and beyond