IPv6: do not call constructor in reload
a) it is already called in __load_from_db()

b) we change all attributes later in reload()

c) child of Device class has different parameters of constructor - they accept dictionary of params instead of name of table

addressing:
Exception Handler Information
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/spacewalk/server/apacheRequest.py", line 123, in call_function
    response = apply(func, params)
  File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line 995, in refresh_hw_profile
    server.delete_hardware()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_wrapper.py", line 87, in delete_hardware
    return Hardware.delete_hardware(self, self.server.get("id"))
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 876, in delete_hardware
    self.reload_hardware_byid(sysid)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 923, in reload_hardware_byid
    self.__load_from_db(HardwareDevice, sysid)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 913, in __load_from_db
    dev.reload(sysid)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 220, in reload
    self.__init__(self.__table)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 315, in __init__
    Device.__init__(self, "rhnDevice", fields, dict, mapping)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnServer/server_hardware.py", line 271, in __init__
    dict, mapping)
TypeError: ('Argument passed is not a dictionary', 'rhnDevice', {'desc': 'description'})