start to compile with Java 1.7 because Jasper in Tomcat 8 generates 1.5 incompatible code
java 1.7 devel package on RHEL 6 is not providing java-devel so I need to change this dependency there

error: diamond operator is not supported in -source 1.5
    _jspx_imports_packages = new java.util.HashSet<>();