495778 - process UTF-8 input.
Addressing
Exception Handler Information
Traceback (most recent call last):
  File "/usr/share/rhn/server/apacheUploadServer.py", line 107, in _wrapper
    ret = function(req)
  File "/usr/share/rhn/upload_server/handlers/package_push/package_push.py", line 145, in handler
    relative_path=self.rel_package_path, org_id=self.org_id)
  File "/usr/share/rhn/server/rhnPackageUpload.py", line 239, in push_package
    importer.run()
  File "/usr/share/rhn/server/importlib/importLib.py", line 629, in run
    self.submit()
  File "/usr/share/rhn/server/importlib/packageImport.py", line 297, in submit
    transactional=self.transactional)
  File "/usr/share/rhn/server/importlib/backend.py", line 735, in processPackages
    transactional=transactional)
  File "/usr/share/rhn/server/importlib/backend.py", line 1511, in __processObjectCollection__
    _buildExternalValue(extObject, entry, tbl)
  File "/usr/share/rhn/server/importlib/backend.py", line 2008, in _buildExternalValue
    dict[f] = sanitizeValue(entry[attr], datatype)
  File "/usr/share/rhn/server/importlib/backendLib.py", line 473, in sanitizeValue
    return str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 190: ordinal not in range(128)
(cherry picked from commit dd570b6d10c1e3f008c3c1e4488a402101f5ee2f)