fixing build errors
addressing:
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:190: cannot find symbol
    [javac] symbol  : class MethodInvalidParamException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         throws MethodInvalidParamException {
    [javac]                ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:192: cannot find symbol
    [javac] symbol  : class StringReader
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         StringReader rdr = new StringReader(clientcert);
    [javac]         ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:192: cannot find symbol
    [javac] symbol  : class StringReader
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         StringReader rdr = new StringReader(clientcert);
    [javac]                                ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:195: cannot find symbol
    [javac] symbol  : class ClientCertificate
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         ClientCertificate cert;
    [javac]         ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:197: cannot find symbol
    [javac] symbol  : variable ClientCertificateDigester
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]             cert = ClientCertificateDigester.buildCertificate(rdr);
    [javac]                    ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:198: cannot find symbol
    [javac] symbol  : variable SystemManager
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]             server = SystemManager.lookupByCert(cert);
    [javac]                      ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:200: cannot find symbol
    [javac] symbol  : class IOException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         catch (IOException ioe) {
    [javac]                ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:201: log has private access in com.redhat.rhn.frontend.xmlrpc.BaseHandler
    [javac]             log.error("IOException - Trying to access a system with an " +
    [javac]             ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:203: cannot find symbol
    [javac] symbol  : class MethodInvalidParamException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]             throw new MethodInvalidParamException();
    [javac]                       ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:205: cannot find symbol
    [javac] symbol  : class SAXException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         catch (SAXException se) {
    [javac]                ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:206: log has private access in com.redhat.rhn.frontend.xmlrpc.BaseHandler
    [javac]             log.error("SAXException - Trying to access a " +
    [javac]             ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:208: cannot find symbol
    [javac] symbol  : class MethodInvalidParamException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]             throw new MethodInvalidParamException();
    [javac]                       ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:210: cannot find symbol
    [javac] symbol  : class InvalidCertificateException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]         catch (InvalidCertificateException e) {
    [javac]                ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:211: log has private access in com.redhat.rhn.frontend.xmlrpc.BaseHandler
    [javac]             log.error("InvalidCertificateException - Trying to access a " +
    [javac]             ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:213: cannot find symbol
    [javac] symbol  : class MethodInvalidParamException
    [javac] location: class com.redhat.rhn.frontend.xmlrpc.satellite.SatelliteHandler
    [javac]             throw new MethodInvalidParamException();
    [javac]                       ^
    [javac] /builddir/build/BUILD/spacewalk-java-1.2.89/code/src/com/redhat/rhn/frontend/xmlrpc/satellite/SatelliteHandler.java:215: incompatible types
    [javac] found   : boolean
    [javac] required: int
    [javac]         return ConfigDefaults.get().isMonitoringBackend();