do cast to None earlier to prevent crash if --no-packages is used
ERROR: invalid input syntax for type numeric:
LINE 4:                        values (48, '',...