errata timestamp expects YYYYMMDDHHMISS
fixing
Traceback (most recent call last):
  File "bug", line 41, in <module>
    repo.get_repomd_file()
  File "/usr/lib/python2.6/site-packages/spacewalk/server/repomd/repository.py", line 348, in get_repomd_file
...
    modified = timestamp(modified)
  File "/usr/lib/python2.6/site-packages/spacewalk/common/rhnLib.py", line 84, in timestamp
    raise TypeError("String '%s' is not a YYYYMMDDHHMISS" % s)
TypeError: String '20110523182837.3651460400' is not a YYYYMMDDHHMISS