Need to have separate schema upgrade for PostgreSQL, we do not process schema upgrades with chameleon.
Addressing
ERROR:  syntax error at or near "ENABLE"
LINE 17: ENABLE ROW MOVEMENT
         ^