Need to return new at the end of a trigger function.
Addressing
xmlrpclib.Fault: <Fault -1: 'redstone.xmlrpc.XmlRpcFault: unhandled internal exception: ERROR: -20255 : (cannot_delete_user) - The specified user may not be deleted.'>

which in fact was a
ERROR:  control reached end of trigger procedure without RETURN
CONTEXT:  PL/pgSQL function "rhn_ugm_applicant_fix_fun"