Need to name a subselect.
Addressing
SQLStatementPrepareError: ('subquery in FROM must have an alias at character 210\nHINT:  For example, FROM (SELECT ...) [AS] foo.\n', 0, "\n    insert into rhnActionConfigRevision \n           (id, action_id, server_id, config_revision_id)\n    select sequence_nextval('rhn_actioncr_id_seq'), %(action_id)s, \n           server_id,