fixed table aliases
fixing
  File "/usr/lib/python2.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 269, in _execute_wrapper
    raise rhnSQL.SQLStatementPrepareError(0, str(e), self.sql)
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('missing FROM-clause entry for table "pr"\nLINE 28:            pr.sense,\n                    ^\n', 0, "\n        select\n           'provides',\n           pp.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageProvides pp\n        where\n           pp.package_id = %(package_id)s\n           and pp.capability_id = pc.id\n        union all\n        select\n           'requires',\n           pr.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageRequires pr\n        where\n           pr.package_id = %(package_id)s\n           and pr.capability_id = pc.id\n        union all\n        select\n           'recommends',\n           pr.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageRecommends prec\n        where\n           prec.package_id = %(package_id)s\n           and prec.capability_id = pc.id\n        union all\n        select\n           'supplements',\n           pr.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageSupplements supp\n        where\n           supp.package_id = %(package_id)s\n           and supp.capability_id = pc.id\n        union all\n        select\n           'suggests',\n           pr.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageSuggests sugg\n        where\n           sugg.package_id = %(package_id)s\n           and sugg.capability_id = pc.id\n        union all\n        select\n           'conflicts',\n           pcon.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageConflicts pcon\n        where\n           pcon.package_id = %(package_id)s\n           and pcon.capability_id = pc.id\n        union all\n        select\n           'obsoletes',\n           po.sense,\n           pc.name,\n           pc.version\n        from\n           rhnPackageCapability pc,\n           rhnPackageObsoletes po\n        where\n           po.package_id = %(package_id)s\n           and po.capability_id = pc.id\n        ")