If libvirtd is not running do not throw traceback
addressing:
[Fri Nov 19 10:53:38 2010] up2date
Traceback (most recent call last):
  File "/usr/sbin/rhnreg_ks", line 216, in ?
    cli.run()
  File "/usr/share/rhn/up2date_client/rhncli.py", line 65, in run
    sys.exit(self.main() or 0)
  File "/usr/sbin/rhnreg_ks", line 178, in main
    rhnreg.sendVirtInfo(systemId)
  File "/usr/share/rhn/up2date_client/rhnreg.py", line 619, in sendVirtInfo
    support.refresh()
  File "/usr/share/rhn/virtualization/support.py", line 72, in refresh
    if _is_host_domain():
  File "/usr/share/rhn/virtualization/support.py", line 197, in _is_host_domain
    conn = libvirt.open(None)
  File "/usr/lib/python2.4/site-packages/libvirt.py", line 159, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: unable to connect to '/var/run/libvirt/libvirt-sock': No such file or directory