Need to use date_diff_in_days instead of date arithmetics for PostgreSQL.
Addressing
2010/12/21 14:19:20 -04:00 25939 0.0.0.0: osad/jabber_lib.main('ERROR', 'Traceback (most recent call last):
  File "/usr/share/rhn/osad/jabber_lib.py", line 121, in main
    self.process_forever(c)
  File "/usr/share/rhn/osad/jabber_lib.py", line 179, in process_forever
    self.process_once(client)
  File "/usr/share/rhn/osad/osa_dispatcher.py", line 167, in process_once
    self._tcp_server.notify_jabber_nodes()
  File "/usr/share/rhn/osad/osa_dispatcher.py", line 299, in notify_jabber_nodes
    h.execute()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 166, in execute
    return apply(self._execute_wrapper, (self._execute, ) + p, kw)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 263, in _execute_wrapper
    raise rhnSQL.SQLStatementPrepareError(0, str(e), self.sql)
SQLStatementPrepareError: (\'column "sysdate" does not exist at character 85\
\', 0, "\
        select a.id, sa.server_id, pc.jabber_id,\
               (earliest_action - sysdate) * 86400 delta\
          from\
               rhnServerAction sa,\
               rhnAction a,\
               rhnPushClient pc\
         where pc.server_id = sa.server_id\
           and sa.action_id = a.id\
           and sa.status in (0, 1) -- Queued or picked up\
           and not exists (\
               -- This is like saying \'this action has no\
               -- prerequisite or has a prerequisite that has completed\
               -- (status = 2)\
               select 1\
                 from rhnServerAction sap\
                where sap.server_id = sa.server_id\
                  and sap.action_id = a.prerequisite\
                  and sap.status != 2\
            )\
         order by earliest_action\
    ")
')