added available_fve_chan_subs to postgresql rhn_channel.pkb
fixing
ERROR:  function rhn_channel.available_fve_chan_subs(bigint, bigint) does not exist at character 8
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  select rhn_channel.available_fve_chan_subs($1, $2) as entitlements from dual