on el5 do not send IPv6 addresses
this will require python-ethtool >= 0.4, which will require libnl >= 1.1, which is not there
so on el5 we will get here
AttributeError: 'module' object has no attribute 'get_interfaces_info'
lets ignore it.