Replace sysdate with current_timestamp.
Addressing
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('column "sysdate" does not exist at character 37\n', 0, 'update rhnChannel set LAST_SYNCED = sysdate\n                             where label = %(channel)s')