983999 - put the 1st element of the python search path to the end
keeping content of search path, changing just the order for finding yum
rpmUtils module instead of our one in the working directory
(not a nice solution)

addressing:
Traceback (most recent call last):
  File "/usr/share/rhn/up2date_client/hardware.py", line 24, in <module>
    import rhnserver
  File "/usr/share/rhn/up2date_client/rhnserver.py", line 34, in <module>
    import rpcServer
  File "/usr/share/rhn/up2date_client/rpcServer.py", line 12, in <module>
    import clientCaps
  File "/usr/share/rhn/up2date_client/clientCaps.py", line 10, in <module>
    from capabilities import parseCap
  File "/usr/share/rhn/up2date_client/capabilities.py", line 4, in <module>
    import up2dateErrors
  File "/usr/share/rhn/up2date_client/up2dateErrors.py", line 44, in <module>
    from yum.Errors import YumBaseError
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 52, in <module>
    import config
  File "/usr/lib/python2.6/site-packages/yum/config.py", line 40, in <module>
    import rpmUtils.transaction
ImportError: No module named transaction