fix creating of groups(PG)
addressing:
2010-11-08 11:41:23,852 [TP-Processor1] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: SELECT
...
           FROM  rhn_check_probe CP, rhn_probe_state PS, rhnServerGroupMembership SGM
          WHERE  PS.probe_id = CP.probe_id
            AND  SGM.server_id = CP.host_id(+)
...
com.redhat.rhn.common.db.WrappedSQLException: ERROR: syntax error at or near ")"
    at com.redhat.rhn.common.translation.SqlExceptionTranslator.postgreSqlException(SqlExceptionTranslator.java:56)
...

and

ERROR:  function decode(character varying, unknown, integer, unknown, integer, unknown, integer, unknown, integer, unknown, integer) does not exist
LINE 11:                   MAX(DECODE(PS.state, 'OK', 1, 'PENDING', 2...
                               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.