add missing import
Related commit: 8cf8bbcd7cd6fcddde01df5032994c857107abcc

This is to avoid traceback during reposync:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 72, in ?
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 66, in main
    sync.main()
  File "/usr/share/rhn/satellite_tools/reposync.py", line 108, in main
    taskomatic.add_to_repodata_queue_for_channel_package_subscription(
NameError: global name 'taskomatic' is not defined