Fedora 19 does not provide /sbin/runuser
Everything has been moved to /usr
addressing:
DEBUG util.py:257:  Error: Package: nocpulse-common-2.2.4-3.fc18.noarch (build)
DEBUG util.py:257:             Requires: /sbin/runuser