Sorting fix in packages for PostgreSQL
This is correction of commit 783c4bc72099f07742978d9ca76e897fba2ed348 that was previously
reverted. This one applies only to NON DISTINCT queries.

Postgres does not allow sorting of string-concatenated columns. We have
many sorts in our java code (package management). This was fixed by
sorting based on columns and not the concatenated string.

Example fix follows. In the statement

SELECT xxx || yyy AS NVRE
...
ORDER BY UPPER(NVRE)

the order by clause is rewritten as

ORDER BY UPPER(xxx), UPPER(yyy)

com.redhat.rhn.common.db.WrappedSQLException: ERROR: column "nvre" does
not exist