683200 - simplify idn_pune_to_unicode and idn_ascii_to_pune
as side effect it will work for hostname with trailing dot (which is valid url)
addressing:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/rhn/up2date_client/config.py", line 312, in getServerlURL
    return [convert_url_to_pune(cfg['serverURL'])]
  File "/usr/share/rhn/up2date_client/config.py", line 294, in convert_url_to_pune
    return urlunsplit((s[0], idn_ascii_to_pune(s[1]), s[2], s[3], s[4])).encode('utf-8')
  File "/usr/lib/python2.6/site-packages/rhn/connections.py", line 230, in idn_ascii_to_pune
    return '.'.join([encodings.idna.ToASCII(x) for x in hostname.split('.')])
  File "/usr/lib64/python2.6/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long