allow channel administrator to view Channel > Managers page
fixing
You do not have sufficient permissions to perform this action.

com.redhat.rhn.common.security.PermissionException: Lookup user requires Org Admin
at com.redhat.rhn.manager.user.UserManager.lookupUser(UserManager.java:529)