915287 - define a utf8_encode wrapper
rhncli does not define utf8_encode on RHEL5, so to prevent changing
rhn-client-tools package in RHEL5, we're doing the change in RHN Tools
package

addressing:
Traceback (most recent call last):
  File "/usr/sbin/rhn-profile-sync", line 54, in ?
    cli.run()
  File "/usr/share/rhn/up2date_client/rhncli.py", line 66, in run
    sys.exit(self.main() or 0)
  File "/usr/sbin/rhn-profile-sync", line 49, in main
    support.refresh(True)
  File "/usr/share/rhn/virtualization/support.py", line 62, in refresh
    if _is_host_domain(fail_on_error):
  File "/usr/share/rhn/virtualization/support.py", line 190, in _is_host_domain
    sys.stderr.write(rhncli.utf8_encode(_("Warning: Could not retrieve virtualiz
ation information!\n\tlibvirtd service needs to be running.\n")))
exceptions.AttributeError: 'module' object has no attribute 'utf8_encode'