require python2 version of rhn-client-tools on all platforms
fixing Fedora 26 issue
$ satellite-sync -m dump/ -l
Unable to find synchronization tools.
Error: No module named up2date_client
 `