fixed sysdate error (PG)
fixing
ERROR:  column "sysdate" does not exist at character 437
STATEMENT:      SELECT instance_id,netsaint_id,command_line,effective_user,effective_gro
up,restartable,notify_email,timeout,target_type,TO_CHAR(expiration_date, 'YYYY MM DD HH2
4 MI SS')
            FROM   rhn_command_queue_commands cmd, rhn_command_queue_instances ins, rhn_
command_queue_execs exec

        WHERE netsaint_id = $1 AND target_type = $2 AND exec.instance_id = ins.recid AND
 ins.command_id = cmd.recid AND date_executed is null AND expiration_date > sysdate