replaced check_probe synonym with original table
fixing
com.redhat.rhn.common.db.datasource.CachedStatement - Error while
processing cached statement sql: SELECT C.description,
       count(p.recid) probe_count,
       count(S.id) server_count
  FROM rhn_probe P, rhn_command C, rhn_command_groups CG, rhnServer S,
       rhn_probe_state PS, rhnUserServerPerms USP
  where P.command_id = C.recid
    AND C.group_name = CG.group_name
    AND P.recid = PS.probe_id
    AND PS.state = ?
    AND P.customer_id = ?
    AND S.id = (SELECT host_id from check_probe where probe_id =
P.recid)
   AND  USP.user_id = ?
   AND  USP.server_id = S.id
  GROUP BY CG.description, C.description
ORDER BY CG.description
com.redhat.rhn.common.db.WrappedSQLException: ERROR: relation
"check_probe" does not exist