max_bytes is unused
fixing
 File "/usr/lib/python2.7/site-packages/spacewalk/satellite_tools/exporter/exportLib.py", line 131, in dump
    self._writer.data(self._value, self._max_value_bytes)
TypeError: data() takes exactly 2 arguments (3 given)

caused by changes in d786bfa1b996536eec0ce73544be342b5e135673