yum-rhn-plugin requires m2crypto
addressing:
Traceback (most recent call last):
  File "/usr/lib/yum-plugins/rhnplugin.py", line 43, in <module>
    from M2Crypto.SSL import SSLError, Connection
ImportError: No module named M2Crypto.SSL