sgmlop parser could not return data in utf-8
Sgmlop does not have returns_unicode unicode. Or something similar.

For more info see:
https://www.redhat.com/archives/spacewalk-list/2011-May/msg00091.html

addressing:
  [Wed May 11 14:56:52 2011] [error] [client 212.219.57.224] PythonHeaderParserHandler spacewalk.server.apacheServer::HeaderParserHandler:   File "/usr/lib/python2.4/site-packages/spacewalk/server/apacheRequest.py", line 64, in __init__\n    self.parser._parser.returns_unicode = 0
  [Wed May 11 14:40:17 2011] [error] [client 212.219.57.197] PythonHeaderParserHandler spacewalk.server.apacheServer::HeaderParserHandler: AttributeError: SgmlopParser instance has no attribute '_parser'