Stop building spacewalk-schema on RHEL 6 until the buildroot issue is resolved.
The root.log says
DEBUG backend.py:680:  /usr/bin/yum --installroot /var/lib/mock/dist-6E-sw-1.3-build-10999-1955/root/  install  'perl(Digest::SHA1)' 'chameleon'
DEBUG util.py:301:  Executing command: /usr/bin/yum --installroot /var/lib/mock/dist-6E-sw-1.3-build-10999-1955/root/  install  'perl(Digest::SHA1)' 'chameleon' --setopt=tsflags=nocontexts
DEBUG util.py:267:  Error: Package: chameleon-0.2-1.el6.noarch (build)
DEBUG util.py:267:             Requires: python-ply
DEBUG util.py:267:   You could try using --skip-broken to work around the problem
DEBUG util.py:267:   You could try running: rpm -Va --nofiles --nodigest
DEBUG util.py:340:  Child returncode was: 1