1704425 - fixed postgresql timestamp handling
fixing
error: function to_timestamp(timestamp with time zone, unknown) does not exist

(cherry picked from commit c1034dac3327a4333f085ec5bff30650a9ac6545)