fix rhnChannel instance has no attribute 'get'
getChannels.channels() returns a list, which doesn't have a 'get' attribute like a dict.
This fixes an AttributeError exception while running `spacewalk-channel -b`.