do not pass string params, when numeric are expected(PG)
adressing:
2010-11-08 11:30:21,684 [TP-Processor3] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: SELECT DISTINCT KS.id, KS.org_id, KS.label,
         KS.active,  KSD.kstree_id,KS.cobbler_id ,KT.label as tree_label,
         c.label as channel_label,
         KS.ks_type as kickstart_type
    FROM rhnKickstartDefaults KSD
         inner join rhnKSData KS on KSD.kickstart_id = KS.id
         inner join rhnKickstartableTree KT on KSD.kstree_id = KT.id
         left join rhnKickstartVirtualizationType KVT on KVT.id = KSD.virtualization_type
     inner join rhnChannel C on KT.channel_id = C.id
   WHERE KS.org_id = ?
     AND KS.active = 'Y'
     AND ( C.channel_arch_id = ? OR C.channel_arch_id = ? )
     AND (   KVT.label != 'xenpv'
          OR KVT.label IS NULL)
     AND KS.cobbler_id IS NOT NULL
ORDER BY KS.label, KS.id
com.redhat.rhn.common.db.WrappedSQLException: ERROR: operator does not exist: numeric = character varying
    at com.redhat.rhn.common.translation.SqlExceptionTranslator.postgreSqlException(SqlExceptionTranslator.java:56)
...