fixing typo
which causes
2012-11-02 07:36:15,476 [TP-Processor12] ERROR
com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing
cached statement sql: select s.id as id,
       s.name as name,
       1 as selectable,
       count(sp.name_id) as extra_pkg_count
  from rhnServer s
...
 where (p.id is null or scp.package_id is null) and
       s.org_id = ?
 group by s.name, s.id
 order by name, id;
com.redhat.rhn.common.db.WrappedSQLException: ORA-00911: invalid character
(cherry picked from commit 6debf9b908b02a5b6084f76b802645b09c199581)