add missing import sys
addressing:
File "/usr/lib/python2.6/site-packages/spacewalk/server/rhnPackageUpload.py", line 292, in load_package
    raise rhnFault(50, "Unable to load package", explain=0), None, sys.exc_info()[2]
NameError: global name 'sys' is not defined