import Fault from different class
object Fault has been previously imported by rhnAuthProtocol,
this import has been removed in commit 94addd571f4538d4351e0b436edb6d1a10c087e3
so our import fail

addressing:
[Tue Nov 30 17:58:26 2010] [error] [client 10.34.26.6] PythonCleanupHandler proxy.apacheServer::CleanupHandler:   File "/usr/share/rhn/proxy/rhnAuthCacheClient.py", line 28, in ?\n    from rhnAuthProtocol import CommunicationError, Fault, send, recv
[Tue Nov 30 17:58:26 2010] [error] [client 10.34.26.6] PythonCleanupHandler proxy.apacheServer::CleanupHandler: ImportError: cannot import name Fault