515575 - require recent rhn-client tools
We need defined exception InvalidRedirectionError
addressing:
  File "/usr/lib/yum-plugins/rhnplugin.py", line 318, in _getFile
    except up2dateErrors.InvalidRedirectionError, e:
AttributeError: 'module' object has no attribute 'InvalidRedirectionError'