Use e.pgerror instead of e.message for psycopg2.OperationalError.
Addressing
  File "/usr/share/rhn/server/rhnSQL/__init__.py", line 118, in initDB
    __init__DB(backend, host, port, username, password, database)
  File "/usr/share/rhn/server/rhnSQL/__init__.py", line 52, in __init__DB
    __DB.connect()
  File "/usr/share/rhn/server/rhnSQL/driver_postgresql.py", line 131, in connect
    return self.connect(reconnect=0)
  File "/usr/share/rhn/server/rhnSQL/driver_postgresql.py", line 135, in connect
    [self.database, -1, e.message])
AttributeError: OperationalError instance has no attribute 'message'