Prevent all nulls in a chunk (which are treated as strings) from affecting the subsequent chunks.
We clear self->bindVariables so that list of all nulls
in the previous chunk which caused the type to be set to
string does not affect our chunk which may have number
there.

Addressing
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_cx_Oracle.py", line 98, in _execute_wrapper
    retval = apply(function, p, kw)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_cx_Oracle.py", line 189, in _executemany
    self._real_cursor.executemany(None, arr)
TypeError: expecting string or buffer data