683200 - refactor rhnMail to use python smtplib
rhnMail has problem sending unicode characters, instead of fixing this I choosed
to use python standard module

addressing:
Standard-error: ERROR: upon attempt to write to log file: 'ascii' codec can't encode character u'\u017e' in position 65: ordinal not in range(128)ERROR: upon attempt to write to log file: 'ascii' codec can't encode character u'\u017e' in position 119: ordinal not in range(128)Traceback (most recent call last):
  File "/usr/bin/satellite-sync", line 175, in ?
    systemExit_exception(7, "SYNC ERROR: attempting to display as much information as possible:", e)
  File "/usr/bin/satellite-sync", line 125, in systemExit_exception
    satsync.sendMail(forceEmail=1)
  File "/usr/lib/python2.4/site-packages/spacewalk/satellite_tools/satsync.py", line 362, in sendMail
    rhnMail.send(headers, body, sender=sndr)
  File "/usr/lib/python2.4/site-packages/spacewalk/common/rhnMail.py", line 71, in send
    os.write(write, "\n%s\n" % body)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 48: ordinal not in range(128)