fix system-profiles report to expect multiple virtual guests per host
addressing:
psycopg2.ProgrammingError: more than one row returned by a subquery used as an expression