Skip the extra lines sent by Apt
Which is a new with Apt-0.8.13.

Addressing:
25% [Working]Traceback (most recent call last):
  File "/usr/lib/apt/methods/spacewalk.distrib", line 261, in <module>
    ret = method.run()
  File "/usr/lib/apt/methods/spacewalk.distrib", line 88, in run
    msg = self.__get_next_msg()
  File "/usr/lib/apt/methods/spacewalk.distrib", line 52, in __get_next_msg
    result['number'] = int(s[0])
ValueError: invalid literal for int() with base 10: ''