Make sure to not iterate through null.
The previous checks for existence and isDirectory() are not
enough, because the directory might not be accessible
(think of permission).

Addressing:
2013-07-30 11:18:12,993 [TP-Processor8] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
javax.el.ELException: Error reading 'files' on type com.redhat.rhn.domain.audit.XccdfTestResult
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:66)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:118)
	at org.apache.el.parser.AstEmpty.getValue(AstEmpty.java:45)
	at org.apache.el.parser.AstNot.getValue(AstNot.java:42)
        ...
Caused by: java.lang.NullPointerException
        at com.redhat.rhn.manager.audit.scap.file.ScapFileManager.lookupFilesForTestResult(ScapFileManager.java:47)
        at com.redhat.rhn.domain.audit.XccdfTestResult.getFiles(XccdfTestResult.java:231)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:62)
        ... 58 more