osad: fix traceback if http proxy is not configured
Addressing:

Starting osad: Error caught:
Traceback (most recent call last):
  File "/usr/share/rhn/osad/jabber_lib.py", line 119, in main
    c = self.setup_connection(no_fork=no_fork)
  File "/usr/share/rhn/osad/jabber_lib.py", line 253, in p_connection
    c = self._get_jabber_client(js)
  File "/usr/share/rhn/osad/jabber_lib.py", line 304, in _jabber_client
    jabberpy_proxy_dict = {'host': cf['proxy_url'].split(':')[0],
KeyError: 'proxy_url'

(cherry picked from commit af3e9a28b3016cb733c375573fa247c2df7bda53)