fixed Notification Methods (PG)
ERROR:  function decode(character varying, unknown, character varying,
unknown, character varying) does not exist at character 70