sys.stderr.write() expects string not bytes
fixing
Traceback (most recent call last):
  File "/usr/bin/rhn-ssl-tool", line 50, in <module>
    sys.exit(mod.main() or 0)
  File "/usr/lib/python3.7/site-packages/certs/rhn_ssl_tool.py", line 1298, in main
    writeError(e)
  File "/usr/lib/python3.7/site-packages/certs/rhn_ssl_tool.py", line 1275, in writeError
    sys.stderr.write(bstr('\nERROR: %s\n' % e))
TypeError: write() argument must be str, not bytes