555659 - do not freak out when SUNW_PATCHID do not have SUN format
addressing:
File "/opt/redhat/rhn/solaris/usr/bin/up2date", line 236, in ?
  main(sys.argv[1:])
File "/opt/redhat/rhn/solaris/usr/bin/up2date", line 209, in main
  exitcode = iface.run(opts.command, opts.argv)
File
"/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/interfaces/up2date/interface.py",
line 209, in run
  pkgs = self.getRHNPackages(latest=True)
File
"/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/interfaces/up2date/interface.py",
line 56, in getRHNPackages
  if reload: self._ctrl.reloadChannels()
File "/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/control.py",
line 375, in reloadChannels
  self._cache.load()
File
"/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/backends/solaris/loader.py",
line 78, in load
  for info in self.getInfoList():
File
"/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/backends/solaris/loader.py",
line 157, in getInfoList
  info = parsePatchLine(entry.rstrip())
File
"/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/backends/solaris/loader.py",
line 515, in parsePatchLine
  info = createPatchInfo(patch, packages, requires, obsoletes, conflicts)
File
"/opt/redhat/rhn/solaris/lib/python2.4/site-packages/smart/backends/solaris/loader.py",
line 550, in createPatchInfo
  (name, prvversion) = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'