Replacing NVL with COALESCE function (PG)
Addressing

ERROR:  function nvl(integer, integer) does not exist at character 1064
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  SELECT distinct E.id, E.advisory, E.advisory_type, E.advisory_name,
                 E.synopsis, TO_CHAR(E.update_date, 'YYYY-MM-DD') AS update_date,
                 COALESCE(((SELECT 1
                                        FROM rhnErrata E2, rhnErrataCloned EC
                                       WHERE E2.org_id = $1
                                         AND EC.id = E2.id
                                         AND EC.original_id = E.id)
                          UNION (SELECT 1
                                        FROM rhnErrataTmp ET, rhnErrataClonedTmp EC2
                                       WHERE ET.org_id = $2
                                         AND EC2.id = ET.id
                                         AND EC2.original_id = E.id)), 0) AS ALREADY_CLONED
            FROM rhnErrata E, rhnChannelErrata CE
           WHERE CE.errata_id = E.id
             AND exists (SELECT 1
                           FROM rhnChannelCloned CC,
                                rhnChannel C
                          WHERE C.org_id = $3
                            AND CC.id = C.id
                            AND CC.original_id = CE.channel_id
                            AND                            NVL(((SELECT 1
                                        FROM rhnErrata E2, rhnErrataCloned EC
                                       WHERE E2.org_id = $4
                                         AND EC.id = E2.id
                                         AND EC.original_id = E.id)
                          UNION (SELECT 1
                                        FROM rhnErrataTmp ET, rhnErrataClonedTmp EC2
                                       WHERE ET.org_id = $5
                                         AND EC2.id = ET.id
                                         AND EC2.original_id = E.id)), 0) = 0)
        ORDER BY update_date DESC, E.id