new logrotate complains about permissions
fixing
error: skipping "/var/log/rhn/osa-dispatcher.log" because parent directory has
insecure permissions (It's world writable or writable by group which is not
"root") Set "su" directive in config file to tell logrotate which user/group
should be used for rotation.