There is no cursor() function for inline cursors in PostgreSQL, using custom function get_hw_info_as_clob instead.
This also makes concat_list_clob not needed, dropping.

Addressing
spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: ('function cursor(text) does not exist at character 1288 ...