fixed misspelled table name
fixing
ERROR:  relation "rhn_command_parameter_threshold" does not exist at character 1188

introduced by commit 475bd021f86a714d630401e66d10421b2e12dc6e