do not re-init the exception cause with the same
- the code looks strange as it sets the exception cause within the constructor and
then tries to re-init it again with the identical cause
- I do not want to change the behavior at this stage, so I'm just avoiding
another exception being thrown

addressing:
java.lang.IllegalStateException: Can't overwrite cause
at java.lang.Throwable.initCause(Throwable.java:337)
at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:189)