Revert "do not reuse system CLASSPATH variable"
This reverts commit e3671b287b059783fdd7ffc784fae691276ac833.

Reverting because it breaks spacewalk-java build with:
    [javac] /usr/src/redhat/BUILD/spacewalk-java-git-2.dd05ab2/code/internal/src/com/redhat/rhn/internal/doclet/ApiCall.java:17: package com.sun.javadoc does not exist
    [javac] import com.sun.javadoc.MethodDoc;
    [javac]                       ^
    [javac] /usr/src/redhat/BUILD/spacewalk-java-git-2.dd05ab2/code/internal/src/com/redhat/rhn/internal/doclet/ApiCall.java:37: cannot find symbol
    [javac] symbol  : class MethodDoc
    [javac] location: class com.redhat.rhn.internal.doclet.ApiCall
    [javac]     private MethodDoc method;
    [javac]             ^