On RHEL 5, we need to explicitly name postgresql84-contrib.
Addressing
postgresql84-8.4.9-1.el5_7.1.x86_64 from installed has depsolving problems
  --> postgresql84 conflicts with postgresql
Error: postgresql84 conflicts with postgresql