Revert "Revert "Fix numeric/smallint incompatible types in PostgreSQL.""
This reverts commit aee6131d9f6f2a9df2b5ed737e3fbaa04e8690eb.

We need to make the schema consistent otherwise on PostgreSQL we get
errors like

	ERROR:  foreign key constraint ... cannot be implemented
	DETAIL: Key columns ... and ... are of incompatible types: numeric and smallint.

We shall sort out the schema upgrade later, so the upgrade script is not
included.